baseURL: "https://unstuck-in-time.github.io/"
title: "Unstuck In Time"
theme: [PaperMod]

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
mainsections: ["posts"]

minify:
  disableXML: true
  minifyOutput: true

languages:
  en:
    languageName: "English"
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series
    menu:
      main:
        - name: Archive
          url: archives
          weight: 5
        - name: Search
          url: search/
          weight: 10
        - name: Tags
          url: tags/
          weight: 10

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  description: "Unstuck In Time - Perpetual overthinking through Cognitive Science and Philosophy"
  author: Arthur Klein
  defaultTheme: auto
  ShowShareButtons: true
  ShowReadingTime: true
  # disableSpecial1stPost: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowAllPagesInArchive: true
  ShowPageNums: true
  ShowToc: true
  tocOpen: true
  comments: true
  showWordCount: true
  images: ["images/pipe.jpg"]


  homeInfoParams:
    Title: "Unstuck In Time"
    Content: >
      Perpetual overthinking through Cognitive Science and Philosophy
  socialIcons:
    - name: Substack
      title: Substack blog
      url: "https://unstuckntime.substack.com/"
    - name: Medium
      title: Medium blog
      url: "https://medium.com/@unstuck-in-time"

  editPost:
    URL: "https://github.com/unstuck-in-time/unstuck-in-time.github.io/tree/main/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  assets:
    disableHLJS: true
    favicon: "favicon/favicon.ico"
    favicon16x16: "favicon/favicon-16x16.png"
    favicon32x32: "favicon/favicon-32x32.png"
    apple_touch_icon: "favicon/apple-touch-icon.png"
    safari_pinned_tab: "favicon/apple-touch-icon.png"
  cover:
      hidden: false # hide everywhere but not in structured data
      hiddenInList: true # hide on list pages and home
      hiddenInSingle: false # hide on single page

  # fuseOpts:
  #     isCaseSensitive: false
  #     shouldSort: true
  #     location: 0
  #     distance: 1000
  #     threshold: 0.4
  #     minMatchCharLength: 0
  #     keys: ["title", "permalink", "summary", "content"]

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
