name: Update Articles Summary

on:
  schedule:
    - cron: '0 0 * * 0' # Every Week
  workflow_dispatch:

jobs:
  update-summary:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          cd reading-summary && pip install -r requirements.txt

      - name: Run summarize relevant articles
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          SCRAPINGANT_TOKEN: ${{ secrets.SCRAPINGANT_TOKEN }}
        run: cd reading-summary && python summarize_articles.py

      - name: Commit changes to a new branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Create a branch name with a timestamp
          BRANCH_NAME="auto/articles-summary-$(date +%Y%m%d-%H%M%S)"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Create pull request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "Update Articles Summary [auto]"
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.BRANCH_NAME }}
          base: main
          title: "Update Articles Summary [auto]"
          body: "This PR updates the weekly article summaries automatically"
          delete-branch: true